### ISSUE TITLE
Compare to other existing solutions

### ISSUE THREAD

**Issue by elgalu** [zalando/ui-automation-chrome-extension#1]
It would be nice to see in the docs how this project compares to others / similar ;)

**Comment by LauriZalando** [comment]
+1.

**Comment by semonte** [comment]
I agree. We still have some features we'll work on and then do a comparison.

**Comment by manoj9788** [comment]
I am interested in working on this project. Unsure where and what to work on lol ;)

**Comment by semonte** [comment]
Hi @manoj9788, you can take a look at issue https://github.com/zalando/ui-automation-chrome-extension/issues/15 :)

**Comment by LappleApple** [comment]
Hi @manoj9788, are you still interested in helping? Issue #15 remains open.
